[env:lolin_s3_mini]
platform = espressif32@6.9.0
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200

; Tùy chỉnh bộ nhớ
board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs
lib_ldf_mode = deep+

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=1
    -D LV_MEM_CUSTOM=1
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=5
    -D TFT_MISO=6
    -D TFT_SCLK=4
    -D TFT_CS=3
    -D TFT_DC=2
    -D TFT_RST=1
    -D TFT_BL=44
    -D SPI_FREQUENCY=27000000
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
lib_ignore =
    SD
    Adafruit SDSelection
    Adafruit ImageReader Library

lib_deps =
    greiman/SdFat @ ^2.2.3
    igorantolic/Ai Esp32 Rotary Encoder @ ^1.7.0
    bodmer/TFT_eSPI @ ^2.5.31
    lvgl/lvgl @ ^8.4.0
    bblanchon/ArduinoJson @ ^6.21.3
extra_scripts = post:auto_rename.py