[env:lolin_s3_mini]
platform = espressif32@6.9.0
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200

; Tùy chỉnh bộ nhớ
board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv
lib_ldf_mode = deep+

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    ; --- CÁC CẤU HÌNH KHÁC ---
    -D BOARD_HAS_PSRAM
    -D LV_CONF_INCLUDE_SIMPLE
    -D NO_GLOBAL_SD
    -D SD_H
    -I src

lib_ignore =
    SD
    Adafruit SDSelection
    Adafruit ImageReader Library

lib_deps =
    greiman/SdFat @ ^2.2.3
    igorantolic/Ai Esp32 Rotary Encoder @ ^1.7.0
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
    adafruit/Adafruit GFX Library @ ^1.12.4
    lvgl/lvgl @ ^8.4.0
    bblanchon/ArduinoJson @ ^6.21.3
extra_scripts = post:auto_rename.py